hobbylive/hobbylive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

hobbylive/products/urls.py
from django.urls import path
from .views import (
    index, products_list, product_detail,
    profile, order, order_detail,
    wishlist, categories, order_accept,
)

app_name = "products"

urlpatterns = [
    path(
        "",
        index,
        name="index"
    ),
    path(
        "products/<int:categories_id>/",
        products_list,
        name="products_list"
    ),
    path(
        "product_detail/<int:pk>_id=<int:img_id>/",
        product_detail,
        name="product_detail"
    ),
    path(
        "profile/",
        profile,
        name="profile"
    ),
    path(
        "order/",
        order,
        name="order"
    ),
    path(
        "order/<int:pk>",
        order_detail,
        name="order_detail"
    ),
    path(
        "wishlist/",
        wishlist,
        name="wishlist"
    ),
    path(
        "categories/",
        categories,
        name="categories"
    ),
    path(
        "order_accept/",
        order_accept,
        name="order_accept"
    )
]

hobbylive/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'signin/',
        LoginView.as_view(template_name='users/signin.html'),
        name='signin'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

hobbylive/products/forms.py
from django import forms
from django.core.exceptions import ValidationError


class QuantityForm(forms.Form):
    qtybutton = forms.IntegerField(
        initial=1,
        min_value=1,
        widget=forms.NumberInput(
            attrs={
                'style': 'text-align: center; width: 50px;',
                'id': 'qtybutton',
            }
        )
    )


class OrderForm(forms.Form):
    choises = (
        ("", "Выберите перевозчика"),
        ("СДЭК", "СДЭК"),
        ("ПочтаРоссии", "ПочтаРоссии"),
    )
    first_name = forms.CharField(
        max_length=255,
        label="Имя"
    )
    last_name = forms.CharField(
        max_length=255,
        label="Фамилия"
    )
    address = forms.CharField(
        max_length=1000,
        label="Город доставки"
    )
    phone_number = forms.CharField(
        max_length=255,
        label="Номер телефона"
    )
    carrier = forms.ChoiceField(
        choices=choises,
        widget=forms.Select(),
        label="Служба доставки"
    )

    def clean_carrier(self):
        carrier = self.cleaned_data.get('carrier')
        if carrier == '':
            raise ValidationError('Пожалуйста, выберите перевозчика.')
        return carrier


class AccountDetailForm(forms.Form):
    first_name = forms.CharField(
        max_length=255,
        label="Имя"
    )
    last_name = forms.CharField(
        max_length=255,
        label="Фамилия"
    )
    username = forms.CharField(
        max_length=255,
        label="Логин"
    )
    email = forms.EmailField(
        max_length=255,
        label="Почта"
    )

hobbylive/products/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db.models import F
from django.shortcuts import render, redirect, get_object_or_404
from .models import (
    Product, Cart, ProductImage,
    Order, ProductInOrder, Wishlist,
    Categories
)
from .forms import QuantityForm, OrderForm, AccountDetailForm


def index(request):
    return render(request, "products/index.html")


def products_list(request, categories_id):
    queryset = Categories.objects.get(id=categories_id).product.all()
    return render(
        request,
        "products/products_list.html",
        {"products": queryset}
    )


def img_not_in_shop_or_wishlist(img_id: int, user, model) -> bool:
    if (img_id,) not in model.objects.filter(user=user).values_list("image"):
        return True
    return False


def product_detail(request, pk, img_id):
    product = get_object_or_404(Product, pk=pk)
    img = get_object_or_404(ProductImage, pk=img_id)
    heart = determine_heart_icon(request.user, img_id)

    form = QuantityForm()

    if request.method == "POST":
        if not request.user.is_authenticated:
            return redirect(
                "users:signin"
            )

        if request.POST.get("image"):
            return redirect(
                "products:product_detail",
                product.pk,
                request.POST.get("image")
            )

        if request.POST.get("action"):
            handle_cart_action(request, product, img)

        if request.POST.get("add_wishlist"):
            handle_wishlist_action(request, product, img)

    return render(
        request,
        "products/product_detail.html",
        {
            "product": product,
            "image_large": img.image.url,
            "form": form,
            "heart": heart,
            "image": img,
        }
    )


def determine_heart_icon(user, img_id):
    return (
        "fa-heart-o"
        if user.is_authenticated and img_not_in_shop_or_wishlist(
            img_id,
            user,
            Wishlist
        ) else "fa-heart"
    )


def handle_cart_action(request, product, img):
    if img_not_in_shop_or_wishlist(img.id, request.user, Cart):
        create_cart_item(request, product, img)
    else:
        update_cart_item(request, img, product)


def create_cart_item(request, product, img):
    data = {
        "user": request.user,
        "product": product,
        "image": img,
        "count": get_cart_count(request, product)
    }
    Cart.objects.create(**data)


def update_cart_item(request, img, product):
    if product.parameters:
        param = request.POST.get("param_value")
        if isinstance(param, int):
            Cart.objects.filter(
                image=img
            ).update(
                parameters_value=F("parameters_value") + param
            )
        else:
            Cart.objects.filter(
                image=img
            ).update(
                count=F("count") + 1
            )
    else:
        Cart.objects.filter(
            image=img
        ).update(
            count=F("count") + request.POST.get("qtybutton")
        )


def get_cart_count(request, product):
    if product.parameters:
        param = request.POST.get("param_value")
        return int(param) // int(
            product.parameters_value.all()[0].value
        ) if param.isdigit() else 1
    return request.POST.get("qtybutton")


def handle_wishlist_action(request, product, img):
    if img_not_in_shop_or_wishlist(img.id, request.user, Wishlist):
        Wishlist.objects.create(user=request.user, product=product, image=img)
    else:
        Wishlist.objects.filter(user=request.user, image=img).delete()


@login_required
def profile(request):
    orders = Order.objects.filter(user=request.user)
    data = {
        "first_name": request.user.first_name,
        "last_name": request.user.last_name,
        "email": request.user.email,
        "username": request.user.username
    }
    form = AccountDetailForm(initial=data)
    if request.method == "POST":
        form = AccountDetailForm(request.POST)
        if form.is_valid():
            data = {
                "first_name": form.data["first_name"],
                "last_name": form.data["last_name"],
                "email": form.data["email"],
                "username": form.data["username"]
            }
            User = get_user_model()
            User.objects.filter(id=request.user.id).update(**data)
    return render(
        request,
        "products/profile.html",
        {
            "orders": orders,
            "form": form,
            "orders_staff": Order.objects.all()
        }
    )


def create_order(user, address, carrier):
    queryset = Cart.objects.filter(user=user)
    total_price = 0
    for elem in queryset:
        total_price += elem.product.price * elem.count
    user_order = Order.objects.create(
        user=user,
        address=address,
        total_price=total_price,
        carrier=carrier
    )
    try:
        for elem in queryset:
            data = {
                "user": user,
                "product": elem.product,
                "image": elem.image,
                "count": elem.count
            }
            if elem.product.parameters:
                data.update(
                    {
                        "parameters": elem.parameters,
                        "parameters_value": elem.parameter_value,
                    }
                )
            product = ProductInOrder.objects.create(**data)
            user_order.products.add(product)
        user_order.save()
        queryset.delete()
    except:
        user_order.delete()
        raise ValidationError("Заказ должен содержать хотя бы один товар")


@login_required
def order(request):
    data = {
        "first_name": request.user.first_name,
        "last_name": request.user.last_name
    }
    form = OrderForm(data)
    if request.method == "POST":
        print("POST")
        if request.POST.get("to_order"):
            print("to_order")
            form = OrderForm(request.POST)
            if form.is_valid():
                data = {
                    "address": request.POST.get("address"),
                    "carrier": request.POST.get("carrier")
                }
                request.session['data'] = data
                return redirect("products:order_accept")
        elif request.POST.get("to_order_pickup"):
            data = {
                "address": "г. Москва, ул. Артюхиной д. 4",
                "carrier": "Самовывоз"
            }
            request.session['data'] = data
            return redirect("products:order_accept")

    return render(
        request,
        "products/order.html",
        {
            "form": form
        }
    )


@login_required
def order_accept(request):
    data = request.session.get("data")
    queryset = Cart.objects.filter(user=request.user)
    total_price = 0
    for elem in queryset:
        total_price += elem.product.price * elem.count
    if request.method == "POST":
        create_order(request.user, data.get("address"), data.get("carrier"))
        return redirect("products:profile")
    return render(
        request,
        "products/order_accept.html",
        {
            "data": data,
            "products": queryset,
            "total_price": total_price
        }
    )


@login_required
def order_detail(request, pk):
    user_order = Order.objects.filter(pk=pk)
    if request.method == "POST":
        user_order.delete()
        return redirect("products:profile")
    return render(
        request,
        "products/order_detail.html",
        {
            "order": user_order[0]
        }
    )


@login_required
def wishlist(request):
    user_wishlist = Wishlist.objects.filter(user=request.user)
    if request.method == "POST":
        if request.POST.get("action"):
            pk = request.POST.get("action")
            wishlist_elem = Wishlist.objects.filter(pk=pk)
            if img_not_in_shop_or_wishlist(
                    wishlist_elem[0].image.id,
                    request.user,
                    Cart
            ):
                Cart.objects.create(
                    user=request.user,
                    product=wishlist_elem[0].product,
                    image=wishlist_elem[0].image,
                    count=1
                )
            else:
                Cart.objects.filter(
                    image=wishlist_elem[0].image
                ).update(count=F("count") + 1)
        else:
            pk = request.POST.get("pk_w")
        Wishlist.objects.filter(pk=pk).delete()
    return render(
        request,
        "products/wishlist.html",
        {
            "wishlist": user_wishlist
        }
    )


def categories(request):
    queryset = Categories.objects.all()
    return render(
        request,
        "products/categories.html",
        {
            "categories": queryset
        }
    )

hobbylive/templates/products/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

hobbylive/templates/products/categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Категории
{% endblock %}
{% block content %}
<style>
    .image_prod {
    height: 400px;
    width: 100%;
    object-fit: cover;
}
    </style>
        <div class="shop-area pt-70 pb-100">
            <div class="container">

                <div class="tab-content jump-3 pt-30">
                        <div class="row">
                            {% for category in categories %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product-wrap mb-50">
                                    <div class="product-img default-overlay mb-25">
                                        <a href="{% url "products:products_list" category.id %}">
                                            <img class="default-img image_prod" src="{{ category.image.url }}" alt="">
                                        </a>
                                    </div>
                                    <div class="product-content-2 title-font-width-400 text-center">
                                        <h2><a href="">{{ category.name }}</a></h2>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>


                </div>
            </div>
        </div>
{% endblock %}

hobbylive/templates/products/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Главная
{% endblock %}
{% block content %}
{#  <div class="top-foto">#}
{#    <img class="image_index" src="{% static "img/index_test.jpg" %}" style="filter: brightness(30%); "  alt="logo">#}
{#  </div>#}
{#  <div class="box">#}
{#  <div class="section-title-1 mb-70 text-center centered">#}
{#      <a class="font-index" >Товары для творческих<br>и изобретательных</a>#}
{#                </div>#}
{#  </div>#}

    <div class="top-foto">
  <img class="image_index" src="{% static 'img/index_test.jpg' %}" style="filter: brightness(30%);" alt="logo">
</div>
<div class="box">
  <div class="section-title-1 mb-70 text-center centered">
    <a class="font-index">Товары для творческих<br>и изобретательных</a>
  </div>
</div>

<style>

</style>
{% endblock %}

hobbylive/templates/products/order.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Оформление заказа
{% endblock %}
{% block content %}
    <div class="breadcrumb-area section-padding-1 bg-gray breadcrumb-ptb-1">
        <div class="container-fluid">
            <div class="breadcrumb-content text-center">
                <div class="breadcrumb-title">

                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <h2  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </h2>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <h2>Оформление заказа</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="my-account-area pt-100 pb-95">
        <div class="container">
            <div class="row flex-row-reverse">
                <div class="col-lg-12">
                    {% if not messages %}
                        <div class="myaccount-tab-menu nav" role="tablist">
                            <a href="#pickup" data-bs-toggle="tab">Самовывоз</a>
                            <a href="#delivery" data-bs-toggle="tab">Доставка</a>
                        </div>
                    {% endif %}
                    <div class="tab-content" id="myaccountContent">
                        <div class="tab-pane fade" id="pickup" role="tabpanel">
                            <div class="login-register-area pt-95 pb-100">
                                <div class="container">
                                    <div class="row justify-content-center">
                                        <div class="col-lg-6 col-md-6">
                                            <div class="login-register-wrap">
                                                <div class="login-register-form">
                                                    Забрать заказ можно по адресу: г. Москва, ул. Артюхиной д. 4 с 10:00
                                                    до 17:00.

                                                    Оформите заказ и на почту Вам придет уведомление о доставке товара в
                                                    пункт самовывоза.
                                                    <form method="post" action={% url "products:order" %}>
                                                        {% csrf_token %}
                                                    <div class="login-register-btn-remember">
                                                            <div class="login-register-btn">
                                                                <button type="submit" name="to_order_pickup" value="ok">Заказать</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="delivery" role="tabpanel">
                            <div class="login-register-area pt-95 pb-100">
                                <div class="container">
                                    <div class="row justify-content-center">
                                        <div class="col-lg-6 col-md-6">
                                            <div class="login-register-wrap">
                                                <div class="login-register-form">
                                                    <form method="post" action={% url "products:order" %}>
                                                        {% csrf_token %}
                                                        {% for elem in form %}
                                                            <div class="sin-login-register">
                                                                <label for="floatingInput">{{ elem.label }}
                                                                    <span>*</span></label>
                                                                {{ elem }}
                                                            </div>
                                                        {% endfor %}
                                                        <div class="login-register-btn-remember">
                                                            <div class="login-register-btn">
                                                                <button type="submit" name="to_order" value="ok2">Заказать</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#    <script>#}
    {#    document.addEventListener('DOMContentLoaded', function() {#}
    {#        const carrierSelect = document.getElementById('id_carrier');#}
    {#        const outputDiv = document.getElementById('output');#}
    {##}
    {#        carrierSelect.addEventListener('change', function() {#}
    {#            if (this.value === "СДЭК") {#}
    {#                outputDiv.textContent = "123";#}
    {#            } else if (this.value === "ПочтаРоссии") {#}
    {#                outputDiv.textContent = "000";#}
    {#            } else {#}
    {#                outputDiv.textContent = ""; // Если ничего не выбрано#}
    {#            }#}
    {#        });#}
    {#    });#}
    {#</script>#}

{% endblock %}

hobbylive/templates/products/order_success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Профиль
{% endblock %}
{% block content %}
    <div class="main-wrapper">
        <div class="breadcrumb-area section-padding-1 bg-gray breadcrumb-ptb-1">
            <div class="container-fluid">
                <div class="breadcrumb-content text-center">
                    <div class="breadcrumb-title">
                        <h2 class="sansa_text">Заказ успешно оформлен</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hobbylive/templates/products/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Профиль
{% endblock %}
{% block content %}


    <body>

    <div class="main-wrapper">

        <div class="breadcrumb-area section-padding-1 bg-gray breadcrumb-ptb-1">
            <div class="container-fluid">
                <div class="breadcrumb-content text-center">
                    <div class="breadcrumb-title">
                        <h2 class="sansa_text">Мой аккаунт ({{ user.username }})</h2>
                        {% if user.is_staff %}
                            <ul>
                                <li class="active">Администратор</li>
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="my-account-area pt-100 pb-95">
            <div class="container">
                <div class="row flex-row-reverse">
                    <div class="col-lg-12">
                        <div class="myaccount-tab-menu nav" role="tablist">
                            <a href="#dashboad" class="active" data-bs-toggle="tab">
                                Информация</a>
                            <a href="#orders" data-bs-toggle="tab">Заказы</a>
                            {% if user.is_staff %}
                                <a href="#orders_staff" data-bs-toggle="tab">Заказы пользователей</a>
                            {% endif %}
                            <a href="#account-info" data-bs-toggle="tab">Детали аккаунта</a>
                            <a href={% url "users:logout" %}>Выход</a>
                        </div>
                        <!-- My Account Tab Menu End -->
                        <!-- My Account Tab Content Start -->
                        <div class="tab-content" id="myaccountContent">
                            <!-- Single Tab Content Start -->
                            <div class="tab-pane fade show active" id="dashboad" role="tabpanel">
                                <div class="myaccount-content">
                                    <div class="welcome">
                                        <p>Привет, <strong>{{ user.get_full_name }}</strong> (Если не <strong>{{ user.get_full_name }}
                                            !</strong><a href="{% url "users:logout" %}" class="logout"> Выйти</a>)</p>
                                    </div>

                                    <p class="mb-0">В личном кабинете. Вы можете просматривать свои заказы, управлять данными аккаунта, а также редактировать свой пароль и данные учетной записи.</p>
                                </div>
                            </div>
                            <!-- Single Tab Content End -->
                            <!-- Single Tab Content Start -->
                            <div class="tab-pane fade" id="orders" role="tabpanel">
                                <div class="myaccount-content">
                                    <div class="myaccount-table table-responsive text-center">
                                        {% if orders %}
                                            <table class="table table-bordered">
                                                <thead class="thead-light">
                                                <tr>
                                                    <th>№</th>
                                                    <th>Дата</th>
                                                    <th>Статус</th>
                                                    <th>Итого</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for order in orders %}
                                                    <tr>
                                                        <td>{{ order.pk }}</td>
                                                        <td>{{ order.date }}</td>
                                                        <td>{{ order.status }}</td>
                                                        <td>₽{{ order.total_price }}</td>
                                                        <td>
                                                            <a href="{% url "products:order_detail" order.pk %}">Перейти</a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        {% else %}
                                            У Вас не было заказов
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <!-- Single Tab Content End -->
                            <div class="tab-pane fade" id="orders_staff" role="tabpanel">
                                <div class="myaccount-content">
                                    <div class="myaccount-table table-responsive text-center">
                                        {% if orders %}
                                            <table class="table table-bordered">
                                                <thead class="thead-light">
                                                <tr>
                                                    <th>№</th>
                                                    <th>Пользователь</th>
                                                    <th>Дата</th>
                                                    <th>Статус</th>
                                                    <th>Итого</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for order in orders_staff %}
                                                    <tr>
                                                        <td>{{ order.pk }}</td>
                                                        <td>{{ order.user.username }}</td>
                                                        <td>{{ order.date }}</td>
                                                        <td>{{ order.status }}</td>
                                                        <td>₽{{ order.total_price }}</td>
                                                        <td>
                                                            <a href="{% url "products:order_detail" order.pk %}">Перейти</a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        {% else %}
                                            У Вас не было заказов
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <!-- Single Tab Content Start -->
                            <div class="tab-pane fade" id="account-info" role="tabpanel">
                                <div class="myaccount-content">
                                    <div class="account-details-form">
                                        <form method="POST">
                                            {% csrf_token %}
                                            {% for elem in form %}
                                                <div class="single-input-item">
                                                    <label for="floatingInput">{{ elem.label }}</label>
                                                    {{ elem }}
                                                </div>
                                            {% endfor %}

                                            <div class="single-input-item">
                                                <button class="check-btn sqr-btn ">Сохранить изменения</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div> <!-- Single Tab Content End -->
                        </div>
                    </div>
                </div>
            </div>
        </div>


{% endblock %}