hobbylive/hobbylive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

hobbylive/products/urls.py
from django.urls import path
from .views import (
    index, products_list, product_detail,
    profile, order, order_detail,
    wishlist, categories, order_accept,
)

app_name = "products"

urlpatterns = [
    path(
        "",
        index,
        name="index"
    ),
    path(
        "products/<int:categories_id>/",
        products_list,
        name="products_list"
    ),
    path(
        "product_detail/<int:pk>_id=<int:img_id>/",
        product_detail,
        name="product_detail"
    ),
    path(
        "profile/",
        profile,
        name="profile"
    ),
    path(
        "order/",
        order,
        name="order"
    ),
    path(
        "order/<int:pk>",
        order_detail,
        name="order_detail"
    ),
    path(
        "wishlist/",
        wishlist,
        name="wishlist"
    ),
    path(
        "categories/",
        categories,
        name="categories"
    ),
    path(
        "order_accept/",
        order_accept,
        name="order_accept"
    )
]

hobbylive/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'signin/',
        LoginView.as_view(template_name='users/signin.html'),
        name='signin'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

hobbylive/templates/includes/footer.html
{% load static %}
<footer class="footer-area bg-black section-padding-1 ">
            <div class="container-fluid">
                <div class="footer-top pt-20 pb-20">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-12">
                        </div>
                        <div class="col-lg-6 col-md-6 col-12">
                            <div class="footer-menu text-center">
                                <nav>
                                    <ul>
                                        <li><a href="#">Контакты</a></li>
                                        <li><a href="#">Самовывоз и Доставка</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-12">
                            <div class="social-icon-style-2 social-icon-right">
                                <a class="facebook" href="tel:+79251631300"><i class="fa fa-mobile-phone"></i></a>
                <a class="dribbble" href="https://wa.me/79251631300?text=%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D0%B9%D1%82%D0%B5%21"><i class="fa fa-whatsapp"></i></a>
                <a class="twitter" href="https://t.me/hobbylivemsk"><i class="fa fa-telegram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-botoom pb-15">
                    <div class="row">
                        <div class="col-12">
                            <div class="copyright text-center">
                                <p>© Все материалы, размещенные на данном сайте, являются интеллектуальной собственностью ИП Калашникова</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

hobbylive/templates/includes/header.html
{% load static %}
{% load mathfilters %}
<header class="header-area  section-padding-1 header_fixed">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-xl-2 col-lg-2">
                <div class="logo logo-width">
                    <a href={% url "products:index" %}>
                        <img src="{% static "img/logo.png" %}" style="width: 60px; height: 60px;" alt="logo">
                    </a>
                </div>
            </div>
            <div class="col-xl-8 col-lg-8 d-flex justify-content-center position-static">

            </div>
            <div class="col-xl-2 col-lg-2">
                <div class="header-right-wrap header-right-flex">
                    <div class="same-style header-wishlist">
                        <a href="{% url "products:wishlist" %}"><i class="fa fa-heart-o"></i></a>
                    </div>
                    <div class="same-style cart-wrap">
                        <a href="#" class="cart-active">
                            <i class="dlicon shopping_bag-20"></i>
                            {% if count > 0 %}
                                <span class="count-style">{{ count }}</span>
                            {% endif %}
                        </a>
                    </div>
                    <div class="same-style header-search">
                        <a class="search-active" href="#">
                            <i class="dlicon ui-1_zoom"></i>
                        </a>
                    </div>
                    <div class="same-style header-off-canvas">
                        <a class="header-aside-button" href="#">
                            <i class="dlicon ui-3_menu-left"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="header-small-mobile section-padding-1">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-6">
                <div class="mobile-logo logo-width">
                    <a href="{% url "products:index" %}">
                        <img alt="" style="width: 60px; height: 60px;" src="{% static "img/logo.png" %}">
                    </a>
                </div>
            </div>
            <div class="col-6">
                <div class="mobile-header-right-wrap">
                    <div class="header-right-wrap header-right-flex">
                        <div class="same-style cart-wrap">
                            <a href="#" class="cart-active">
                                <i class="dlicon shopping_bag-20"></i>
                                {% if count > 0 %}
                                    <span class="count-style">{{ count }}</span>
                                {% endif %}
                            </a>
                        </div>
                        <div class="same-style header-off-canvas">
                            <a class="header-aside-button" href="#">
                                <i class="dlicon ui-3_menu-left"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- search start -->
<div class="search-content-wrap main-search-active">
    <a class="search-close"><i class="dlicon ui-1_simple-remove"></i></a>
    <div class="search-content">
        <p>Поиск</p>
        <form class="search-form" method="GET">
            <input type="text" name="q" placeholder="Поиск в каталоге...">
            <button class="button-search"><i class="dlicon ui-1_zoom"></i></button>
        </form>
    </div>
</div>
<!-- mini cart start -->
<div class="sidebar-cart-active">
    <div class="sidebar-cart-all">
        <a class="cart-close" href="#"><i class="dlicon ui-1_simple-remove"></i></a>
        <div class="cart-content">
            <h3>Корзина</h3>
            <ul>
            {% if user.is_authenticated %}
                {% for cart_elem in queryset %}
                    <li class="single-product-cart">
                        <div class="cart-img">
                            <a href="#"><img src="{{ cart_elem.image.image.url }}" alt=""></a>
                        </div>
                        <div class="cart-title">
                            <h4><a href="#">{{ cart_elem.product.name }}{% if cart_elem.image.color %}
                                                ({{ cart_elem.image.color }})
                                                {% endif %}</a></h4>
                            <span>{{ cart_elem.count }} * {{ cart_elem.product.price }}	₽</span>

                        </div>
                        <div class="cart-delete">
                            <form method="POST">
                                {% csrf_token %}
                                <button style="border-style: none; background: none" type="submit" name="pk"
                                        value="{{ cart_elem.pk }}">×
                                </button>
                            </form>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="cart-total">
                <h4>Итого: <span>{{ total_price }} ₽</span></h4>
            </div>
            <div class="cart-checkout-btn">
                <a class="btn-hover cart-btn-style" href="{% url "products:order" %}">Оформить заказ</a>
            </div>
                {% else %}
                Вы ничего не добавили в корзину
            {% endif %}
        </div>
    </div>
</div>
<!-- aside start -->
<div class="header-aside-active">
    <div class="header-aside-wrap">
        <a class="aside-close"><i class="dlicon ui-1_simple-remove"></i></a>
        <div class="header-aside-content">
            <div class="mobile-menu-area">
                <div class="mobile-search">
                    <form class="search-form" action="#">
                        <input type="text" placeholder="Поиск в каталоге…">
                        <button class="button-search"><i class="dlicon ui-1_zoom"></i></button>
                    </form>
                </div>
                <div class="mobile-menu-wrap">
                    <!-- mobile menu start -->
                    <div class="mobile-navigation">
                        <!-- mobile menu navigation start -->
                        <nav>
                            <ul class="mobile-menu">
                                {% if user.is_authenticated %}
                                    <li><a href="{% url "products:profile" %}">Мой аккаунт</a></li>
                                {% else %}
                                    <li><a href="{% url "users:signin" %}">Вход</a></li>
                                    <li><a href="{% url "users:signup" %}">Регистрация</a></li>
                                {% endif %}
                                <li><a href="{% url "products:categories" %}">Каталог</a></li>
{#                                <li><a href="#">Контакты </a></li>#}
{#                                <li><a href="#">Самовывоз и Доставка </a></li>#}
                            </ul>
                        </nav>
                        <!-- mobile menu navigation end -->
                    </div>
                    <!-- mobile menu end -->
                </div>

            </div>
            <div class="header-aside-menu">
                <nav>
                    <ul>
                        {% if user.is_authenticated %}
                            <li><a href="{% url "products:profile" %}">Мой аккаунт</a></li>
                        {% else %}
                            <li><a href="{% url "users:signin" %}">Вход</a></li>
                            <li><a href="{% url "users:signup" %}">Регистрация</a></li>
                        {% endif %}
                        <li><a href="{% url "products:categories" %}">Каталог</a></li>
{#                        <li><a href="#">Контакты </a></li>#}
{#                        <li><a href="#">Самовывоз и Доставка </a></li>#}
                    </ul>
                </nav>
            </div>
            <div class="aside-contact-info">
                <ul>
                    <li><i class="dlicon ui-2_time-clock"></i>Понедельник - Воскресенье: 10:00 - 17:00</li>
                    <li><i class="dlicon ui-1_home-minimal"></i>г. Москва, ул. Артюхиной д. 4</li>
                </ul>
            </div>
            <div class="social-icon-style-2 social-icon">
                <a class="facebook" href="tel:+79251631300"><i class="fa fa-mobile-phone"></i></a>
                <a class="dribbble"
                   href="https://wa.me/79251631300?text=%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D0%B9%D1%82%D0%B5%21"><i
                        class="fa fa-whatsapp"></i></a>
                <a class="twitter" href="https://t.me/hobbylivemsk"><i class="fa fa-telegram"></i></a>
            </div>
            <div class="copyright">
                <p>© 2024 Hobby Live</p>
            </div>
        </div>
    </div>
</div>